name: ğŸš€CI/CD Pipeline

on:
  pull_request:
    branches: ["master"]

jobs:
  CI:
    name: ğŸ”§ Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: ğŸ“¦ Installing dependencies
        run: npm install --legacy-peer-deps

      - name: ğŸ§¹ Linting
        run: npm run lint

      - name: ğŸ§ª Testing
        run: npm test

  CD:
    name: ğŸš¢ Continuous Deployment
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Installing Vercel CLI
        run: npm install -g vercel@latest

      - name: ğŸ“¡ Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: ğŸš€ Deploy project Artifacts
        run: vercel deploy --prebuilt --prd --token=${{ secrets.VERCEL_TOKEN }}
